services:
  sbm-util-dev:
    image: sbm-util:dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sbm-util-dev
    env_file:
      - .env.dev
    ports:
      - "8002:8080"
    volumes:
      - ../../context/documentation/pages:/app/Documentation/sbm-suite
    restart: unless-stopped